services:
  - type: web
    name: blackmamer-obfuscator
    runtime: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y golang-go git
      npm install
      bash build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
