services:
  - type: web
    name: blackmamer-obfuscator-api
    env: node
    buildCommand: |
      npm install
      npm install -g @gamely/prometheus-cli
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    plan: free
